apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-app-feed
  labels:
    app: udagram-app-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-app-feed
  template:
    metadata:
      labels:
        app: udagram-app-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: mabhedlankosi/udagram-api-feed
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRES_USERNAME
                optional: false
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRES_PASSWORD
                optional: false
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRES_HOST
                optional: false
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: POSTGRES_DB
                optional: false
          - name: AWS_BUCKET
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: AWS_BUCKET
                optional: false
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: AWS_REGION
                optional: false
          - name: AWS_PROFILE
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: AWS_PROFILE
                optional: false
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: JWT_SECRET
                optional: false
          - name: URL
            valueFrom:
              secretKeyRef:
                name: env-secret
                key: URL
                optional: false
        ports:
        - containerPort: 80
        imagePullPolicy: Always